// Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ · 微信：zhuatech / zhuatech2
export const statuses = {
  PENDING: "待派工",
  DISPATCHED: "待接单",
  IN_PROGRESS: "处理中",
  WAIT_PARTS: "待料",
  WAIT_CUSTOMER: "待客户",
  REVIEW: "待复核",
  CONFIRM: "待确认",
  CLOSED: "已关闭",
  CANCELLED: "已取消",
  COVERED: "保内服务",
  CHARGEABLE: "收费服务",
  NORMAL: "普通",
  URGENT: "紧急",
  UNSETTLED: "未结算",
  SETTLED: "已结算",
  RECEIVE: "入库",
  ISSUE: "领用",
  RETURN: "退回",
  CONSUME: "消耗",
};
export const permissionNames = {
  "catalog.read": "查看客户设备",
  "catalog.write": "维护客户设备合同",
  "orders.read": "查看工单",
  "orders.create": "创建服务请求",
  "orders.dispatch": "派工与报价",
  "orders.execute": "执行服务",
  "orders.review": "复核服务",
  "orders.confirm": "客户确认",
  "orders.close": "登记结算",
  "orders.cancel": "取消工单",
  "orders.reopen": "重新打开",
  "orders.assigned": "仅查看本人指派工单",
  "inventory.read": "查看备件",
  "inventory.write": "入库领用与退回",
  "plans.manage": "维护维保计划",
  "knowledge.read": "查看已发布知识",
  "knowledge.write": "编辑发布知识",
  "audit.read": "查看审计",
  "report.read": "经营统计与导出",
  "admin.manage": "管理账号角色组织",
};
const field = (key, label, type = "text", required = true) => ({
  key,
  label,
  type,
  required,
});
export const schemas = {
  customers: [
    field("name", "客户名称"),
    field("site", "地址", "text", false),
    field("contact", "业务联系人", "text", false),
    field("enabled", "启用", "checkbox"),
  ],
  assets: [
    field("name", "设备名称"),
    field("customerId", "所属客户", "customers"),
    field("serialNumber", "序列号"),
    field("location", "安装地点", "text", false),
    field("warrantyUntil", "保修截止日", "date", false),
    field("enabled", "启用", "checkbox"),
  ],
  contracts: [
    field("name", "合同名称"),
    field("assetId", "覆盖设备", "assets"),
    field("startDate", "生效日期", "date"),
    field("endDate", "到期日期", "date"),
    field("responseHours", "响应时限（小时）", "number"),
    field("resolutionHours", "完成时限（小时）", "number"),
    field("enabled", "启用", "checkbox"),
  ],
  parts: [
    field("name", "备件名称"),
    field("sku", "备件编码"),
    field("unit", "计量单位"),
    field("unitCost", "标准单位成本（元）", "number"),
    field("enabled", "启用", "checkbox"),
  ],
  plans: [
    field("name", "计划名称"),
    field("assetId", "设备", "assets"),
    field("nextDate", "下次计划日期", "date"),
    field("intervalDays", "间隔天数", "number"),
    field("description", "检查与维护要求", "textarea"),
    field("enabled", "启用", "checkbox"),
  ],
  knowledge: [
    field("name", "标题"),
    field("category", "故障分类"),
    field("content", "解决方案", "textarea"),
    field("published", "发布给部门人员", "checkbox"),
  ],
  config: [
    field("name", "名称"),
    field("kind", "字典或参数类型"),
    field("value", "值"),
    field("enabled", "启用", "checkbox"),
  ],
  users: [
    field("username", "登录账号"),
    field("displayName", "显示姓名"),
    field("orgId", "所属部门", "organizations"),
    field("roleId", "角色", "roles"),
    field("customerId", "客户绑定编号", "customers", false),
    field("password", "密码（至少12位，编辑时可留空）", "password", false),
    field("enabled", "启用", "checkbox"),
  ],
  roles: [
    field("name", "角色名称"),
    field("permissions", "操作权限", "permissions"),
  ],
  organizations: [
    field("name", "部门名称"),
    field("enabled", "启用", "checkbox"),
  ],
  orders: [
    field("name", "服务请求标题"),
    field("assetId", "设备", "assets"),
    field("priority", "优先级", "priority"),
    field("description", "问题与服务要求", "textarea"),
  ],
};
export const columns = {
  customers: [
    ["name", "客户"],
    ["site", "地址"],
    ["contact", "联系人"],
    ["enabled", "状态"],
  ],
  assets: [
    ["name", "设备"],
    ["serialNumber", "序列号"],
    ["customerId", "客户编号"],
    ["location", "安装地点"],
    ["warrantyUntil", "保修截止"],
    ["enabled", "状态"],
  ],
  contracts: [
    ["name", "合同"],
    ["assetId", "设备编号"],
    ["startDate", "生效"],
    ["endDate", "到期"],
    ["responseHours", "响应小时"],
    ["enabled", "状态"],
  ],
  parts: [
    ["name", "备件"],
    ["sku", "编码"],
    ["stock", "库存"],
    ["unit", "单位"],
    ["unitCost", "单位成本"],
    ["enabled", "状态"],
  ],
  plans: [
    ["name", "计划"],
    ["assetId", "设备编号"],
    ["nextDate", "下次日期"],
    ["intervalDays", "间隔天数"],
    ["enabled", "状态"],
  ],
  knowledge: [
    ["name", "标题"],
    ["category", "分类"],
    ["published", "已发布"],
    ["updatedAt", "更新时间"],
  ],
  config: [
    ["name", "名称"],
    ["kind", "类型"],
    ["value", "值"],
    ["enabled", "状态"],
  ],
  users: [
    ["username", "账号"],
    ["displayName", "姓名"],
    ["orgId", "部门编号"],
    ["roleId", "角色编号"],
    ["customerId", "客户绑定"],
    ["enabled", "状态"],
  ],
  roles: [
    ["name", "角色"],
    ["builtin", "内置"],
    ["permissions", "权限"],
  ],
  organizations: [
    ["name", "部门"],
    ["enabled", "状态"],
  ],
  orders: [
    ["name", "服务请求"],
    ["state", "状态"],
    ["assetId", "设备编号"],
    ["coverage", "服务权益"],
    ["priority", "优先级"],
    ["dueAt", "完成时限"],
  ],
  movements: [
    ["kind", "操作"],
    ["partId", "备件编号"],
    ["orderId", "工单编号"],
    ["quantity", "数量"],
    ["unitCost", "单位成本"],
    ["reason", "原因"],
    ["createdAt", "时间"],
  ],
  audit: [
    ["actor", "操作人"],
    ["action", "操作"],
    ["resource", "对象"],
    ["detail", "记录"],
    ["createdAt", "时间"],
  ],
};
export const menus = [
  ["dashboard", "工作台", "orders.read"],
  ["orders", "服务工单", "orders.read"],
  ["customers", "客户资料", "catalog.read"],
  ["assets", "设备台账", "catalog.read"],
  ["contracts", "服务合同", "catalog.read"],
  ["parts", "备件库存", "inventory.read"],
  ["movements", "备件流水", "inventory.read"],
  ["plans", "维保计划", "plans.manage"],
  ["knowledge", "知识库", "knowledge.read"],
  ["audit", "操作审计", "audit.read"],
  ["users", "员工账号", "admin.manage"],
  ["roles", "角色权限", "admin.manage"],
  ["organizations", "组织部门", "admin.manage"],
  ["config", "字典参数", "admin.manage"],
  ["account", "账号设置", "总览"],
];
